name: Unit Tests
on:
  push:
    branches:
      - master
    paths:
      - 'tests/**'
      - 'src/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: UTC
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-tests.txt
      - name: Install the development package itself
        run: |
          python -m pip install -e .
      - name: Run tests with pytest and generate coverage report
        run: pytest --cov=./ --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
