name: Build and Publish Documentation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Sphinx Build and Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y pandoc libgl1-mesa-dev"
        docs-folder: "docs/"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
